#!/usr/bin/python3
import math
import sys



def factors(num):
    if num % 2 == 0:
        divisor = 2
        print(f"{num}={num//divisor}*{divisor}")
    else:
        square_root = int(math.sqrt(num)) + 1
        for i in range(3, square_root, 2):
            if num % i == 0:
                print(f"{num}={num//i}*{i}")
                return
            if num % (square_root + i) == 0:
                print(f"{num}={square_root + i}*{num//(square_root + i)}")
                return
            if num % (square_root - i) == 0:
                print(f"{num}={square_root - 1}*{num//(square_root - i)}")
                return

def read_file_and_print_factors(filename):
    with open(filename, encoding="utf-8") as file:
        for line in file:
            num = int(line)
            factors(num)

if __name__ == "__main__":
    read_file_and_print_factors(sys.argv[1])
